version: '3.7'

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./.env.dev

  # 사용하지 않음
  # my-database:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: 'my_books'
  #     MYSQL_ROOT_PASSWORD: 'root'
  #   ports:
  #     - 3306:3306
